var hierarchy =
[
    [ "core::Allocator< allocaSize, splitDelta >", "structcore_1_1Allocator.html", null ],
    [ "Base", "structBase.html", [
      [ "A", "structA.html", null ],
      [ "B", "structB.html", null ]
    ] ],
    [ "core::CxaAtExitElement", "structcore_1_1CxaAtExitElement.html", null ],
    [ "core::CxaThreadAtExitWrapper", "structcore_1_1CxaThreadAtExitWrapper.html", null ],
    [ "core::Elf32Auxv", "structcore_1_1Elf32Auxv.html", null ],
    [ "core::Elf32AuxvValue", "unioncore_1_1Elf32AuxvValue.html", null ],
    [ "core::Elf64Hdr", "structcore_1_1Elf64Hdr.html", null ],
    [ "core::Elf64Phdr", "structcore_1_1Elf64Phdr.html", null ],
    [ "core::Elf64Shdr", "structcore_1_1Elf64Shdr.html", null ],
    [ "core::Elf64Sym", "structcore_1_1Elf64Sym.html", null ],
    [ "ast::symbolTable::Entry", "structast_1_1symbolTable_1_1Entry.html", null ],
    [ "core::Map< K, V >::Entry", "structcore_1_1Map_1_1Entry.html", null ],
    [ "core::Map< K, V >::EntryList", "structcore_1_1Map_1_1EntryList.html", null ],
    [ "core::ExecutionFutex", "classcore_1_1ExecutionFutex.html", null ],
    [ "core::FdStream", "classcore_1_1FdStream.html", [
      [ "core::FileStream", "classcore_1_1FileStream.html", null ]
    ] ],
    [ "core::FirstTemplateBase< T, Ts >", "structcore_1_1FirstTemplateBase.html", null ],
    [ "core::Function< R, Args >", "classcore_1_1Function.html", null ],
    [ "gssa::Function", "structgssa_1_1Function.html", null ],
    [ "gssa::FunctionAttribute", "structgssa_1_1FunctionAttribute.html", null ],
    [ "core::Allocator< allocaSize, splitDelta >::Header", "structcore_1_1Allocator_1_1Header.html", null ],
    [ "core::Hex", "structcore_1_1Hex.html", null ],
    [ "core::IndicesSequence< Index >", "structcore_1_1IndicesSequence.html", null ],
    [ "core::Function< R, Args >::InvokeResultBase< F, ARGS >", "classcore_1_1Function_1_1InvokeResultBase.html", null ],
    [ "core::IsConstructibleBase< T, Args >", "structcore_1_1IsConstructibleBase.html", null ],
    [ "core::Map< K, V >::Iterator", "classcore_1_1Map_1_1Iterator.html", null ],
    [ "core::MultiSet< T >::Iterator", "classcore_1_1MultiSet_1_1Iterator.html", null ],
    [ "core::Set< T >::Iterator", "classcore_1_1Set_1_1Iterator.html", null ],
    [ "core::String::Iterator", "classcore_1_1String_1_1Iterator.html", null ],
    [ "core::Vector< T >::Iterator", "classcore_1_1Vector_1_1Iterator.html", null ],
    [ "core::Zipped< Iterable1, Iterable2 >::Iterator", "structcore_1_1Zipped_1_1Iterator.html", null ],
    [ "ast::symbolTable::Level", "structast_1_1symbolTable_1_1Level.html", null ],
    [ "core::Logger", "classcore_1_1Logger.html", null ],
    [ "core::LogicalResult< T >", "classcore_1_1LogicalResult.html", null ],
    [ "core::Map< K, V >", "classcore_1_1Map.html", null ],
    [ "core::Map< core::String, core::UniquePtr< ast::StructDeclaration > >", "classcore_1_1Map.html", null ],
    [ "core::Map< core::String, core::UniquePtr< ast::Type > >", "classcore_1_1Map.html", null ],
    [ "core::Map< core::String, core::UniquePtr< ast::UnionDeclaration > >", "classcore_1_1Map.html", null ],
    [ "core::Map< core::String, core::UniquePtr< gssa::Attribute > >", "classcore_1_1Map.html", null ],
    [ "core::MultiSet< T >", "classcore_1_1MultiSet.html", null ],
    [ "core::MultiSet< gssa::Operation * >", "classcore_1_1MultiSet.html", null ],
    [ "core::Mutex", "structcore_1_1Mutex.html", null ],
    [ "ast::Node", "structast_1_1Node.html", [
      [ "ast::AddAffecExpression", "structast_1_1AddAffecExpression.html", null ],
      [ "ast::AddExpression", "structast_1_1AddExpression.html", null ],
      [ "ast::AddrofExpression", "structast_1_1AddrofExpression.html", null ],
      [ "ast::AffecExpression", "structast_1_1AffecExpression.html", null ],
      [ "ast::Argument", "structast_1_1Argument.html", null ],
      [ "ast::ArrayExpression", "structast_1_1ArrayExpression.html", null ],
      [ "ast::ArrayType", "structast_1_1ArrayType.html", null ],
      [ "ast::BandAffecExpression", "structast_1_1BandAffecExpression.html", null ],
      [ "ast::BandExpression", "structast_1_1BandExpression.html", null ],
      [ "ast::BitCastExpression", "structast_1_1BitCastExpression.html", null ],
      [ "ast::BitType", "structast_1_1BitType.html", null ],
      [ "ast::BnotExpression", "structast_1_1BnotExpression.html", null ],
      [ "ast::BorAffecExpression", "structast_1_1BorAffecExpression.html", null ],
      [ "ast::BorExpression", "structast_1_1BorExpression.html", null ],
      [ "ast::BreakStmt", "structast_1_1BreakStmt.html", null ],
      [ "ast::BxorAffecExpression", "structast_1_1BxorAffecExpression.html", null ],
      [ "ast::BxorExpression", "structast_1_1BxorExpression.html", null ],
      [ "ast::CastDeclaration", "structast_1_1CastDeclaration.html", null ],
      [ "ast::CastExpression", "structast_1_1CastExpression.html", null ],
      [ "ast::CharExpression", "structast_1_1CharExpression.html", null ],
      [ "ast::CompoundStmt", "structast_1_1CompoundStmt.html", null ],
      [ "ast::ContinueStmt", "structast_1_1ContinueStmt.html", null ],
      [ "ast::Declarator", "structast_1_1Declarator.html", null ],
      [ "ast::DerefExpression", "structast_1_1DerefExpression.html", null ],
      [ "ast::DivAffecExpression", "structast_1_1DivAffecExpression.html", null ],
      [ "ast::DivExpression", "structast_1_1DivExpression.html", null ],
      [ "ast::DoWhileStmt", "structast_1_1DoWhileStmt.html", null ],
      [ "ast::EqExpression", "structast_1_1EqExpression.html", null ],
      [ "ast::ExpressionStmt", "structast_1_1ExpressionStmt.html", null ],
      [ "ast::FalseExpression", "structast_1_1FalseExpression.html", null ],
      [ "ast::FieldExpression", "structast_1_1FieldExpression.html", null ],
      [ "ast::ForStmt", "structast_1_1ForStmt.html", null ],
      [ "ast::FunExpression", "structast_1_1FunExpression.html", null ],
      [ "ast::FunType", "structast_1_1FunType.html", null ],
      [ "ast::FunctionDeclaration", "structast_1_1FunctionDeclaration.html", null ],
      [ "ast::GeExpression", "structast_1_1GeExpression.html", null ],
      [ "ast::GtExpression", "structast_1_1GtExpression.html", null ],
      [ "ast::IfStmt", "structast_1_1IfStmt.html", null ],
      [ "ast::IntExpression", "structast_1_1IntExpression.html", null ],
      [ "ast::LandAffecExpression", "structast_1_1LandAffecExpression.html", null ],
      [ "ast::LandExpression", "structast_1_1LandExpression.html", null ],
      [ "ast::LeExpression", "structast_1_1LeExpression.html", null ],
      [ "ast::LnotExpression", "structast_1_1LnotExpression.html", null ],
      [ "ast::LorAffecExpression", "structast_1_1LorAffecExpression.html", null ],
      [ "ast::LorExpression", "structast_1_1LorExpression.html", null ],
      [ "ast::LshiftAffecExpression", "structast_1_1LshiftAffecExpression.html", null ],
      [ "ast::LshiftExpression", "structast_1_1LshiftExpression.html", null ],
      [ "ast::LtExpression", "structast_1_1LtExpression.html", null ],
      [ "ast::LxorAffecExpression", "structast_1_1LxorAffecExpression.html", null ],
      [ "ast::LxorExpression", "structast_1_1LxorExpression.html", null ],
      [ "ast::ModAffecExpression", "structast_1_1ModAffecExpression.html", null ],
      [ "ast::ModExpression", "structast_1_1ModExpression.html", null ],
      [ "ast::MulAffecExpression", "structast_1_1MulAffecExpression.html", null ],
      [ "ast::MulExpression", "structast_1_1MulExpression.html", null ],
      [ "ast::NeqExpression", "structast_1_1NeqExpression.html", null ],
      [ "ast::NopStmt", "structast_1_1NopStmt.html", null ],
      [ "ast::OperationDeclaration", "structast_1_1OperationDeclaration.html", null ],
      [ "ast::OtherExpression", "structast_1_1OtherExpression.html", null ],
      [ "ast::PostDecrExpression", "structast_1_1PostDecrExpression.html", null ],
      [ "ast::PostIncrExpression", "structast_1_1PostIncrExpression.html", null ],
      [ "ast::PreDecrExpression", "structast_1_1PreDecrExpression.html", null ],
      [ "ast::PreIncrExpression", "structast_1_1PreIncrExpression.html", null ],
      [ "ast::Program", "structast_1_1Program.html", null ],
      [ "ast::PtrFieldExpression", "structast_1_1PtrFieldExpression.html", null ],
      [ "ast::PtrType", "structast_1_1PtrType.html", null ],
      [ "ast::ReturnStmt", "structast_1_1ReturnStmt.html", null ],
      [ "ast::RshiftAffecExpression", "structast_1_1RshiftAffecExpression.html", null ],
      [ "ast::RshiftExpression", "structast_1_1RshiftExpression.html", null ],
      [ "ast::SizeofExpression", "structast_1_1SizeofExpression.html", null ],
      [ "ast::StringExpression", "structast_1_1StringExpression.html", null ],
      [ "ast::StructDeclaration", "structast_1_1StructDeclaration.html", null ],
      [ "ast::StructType", "structast_1_1StructType.html", null ],
      [ "ast::SubAffecExpression", "structast_1_1SubAffecExpression.html", null ],
      [ "ast::SubExpression", "structast_1_1SubExpression.html", null ],
      [ "ast::SwitchCase", "structast_1_1SwitchCase.html", null ],
      [ "ast::SwitchDefault", "structast_1_1SwitchDefault.html", null ],
      [ "ast::SwitchStmt", "structast_1_1SwitchStmt.html", null ],
      [ "ast::SyscallExpression", "structast_1_1SyscallExpression.html", null ],
      [ "ast::TernaryExpression", "structast_1_1TernaryExpression.html", null ],
      [ "ast::ThisExpression", "structast_1_1ThisExpression.html", null ],
      [ "ast::TrueExpression", "structast_1_1TrueExpression.html", null ],
      [ "ast::TypelessType", "structast_1_1TypelessType.html", null ],
      [ "ast::UnionDeclaration", "structast_1_1UnionDeclaration.html", null ],
      [ "ast::UnionType", "structast_1_1UnionType.html", null ],
      [ "ast::VarExpression", "structast_1_1VarExpression.html", null ],
      [ "ast::VariableDeclaration", "structast_1_1VariableDeclaration.html", null ],
      [ "ast::VoidType", "structast_1_1VoidType.html", null ],
      [ "ast::WhileStmt", "structast_1_1WhileStmt.html", null ]
    ] ],
    [ "core::MultiSet< T >::Node", "structcore_1_1MultiSet_1_1Node.html", null ],
    [ "core::Set< T >::Node", "structcore_1_1Set_1_1Node.html", null ],
    [ "gssa::Operation", "structgssa_1_1Operation.html", [
      [ "gssa::AddrofOperation", "structgssa_1_1AddrofOperation.html", null ],
      [ "gssa::AndOperation", "structgssa_1_1AndOperation.html", null ],
      [ "gssa::CallOperation", "structgssa_1_1CallOperation.html", null ],
      [ "gssa::ConcatOperation", "structgssa_1_1ConcatOperation.html", null ],
      [ "gssa::ConstOperation", "structgssa_1_1ConstOperation.html", null ],
      [ "gssa::DerefOperation", "structgssa_1_1DerefOperation.html", null ],
      [ "gssa::ExtractOperation", "structgssa_1_1ExtractOperation.html", null ],
      [ "gssa::GammaOperation", "structgssa_1_1GammaOperation.html", null ],
      [ "gssa::LoadOperation", "structgssa_1_1LoadOperation.html", null ],
      [ "gssa::MetaOperation", "structgssa_1_1MetaOperation.html", null ],
      [ "gssa::MuOperation", "structgssa_1_1MuOperation.html", null ],
      [ "gssa::NotOperation", "structgssa_1_1NotOperation.html", null ],
      [ "gssa::OrOperation", "structgssa_1_1OrOperation.html", null ],
      [ "gssa::StoreOperation", "structgssa_1_1StoreOperation.html", null ],
      [ "gssa::SyscallOperation", "structgssa_1_1SyscallOperation.html", null ],
      [ "gssa::XorOperation", "structgssa_1_1XorOperation.html", null ]
    ] ],
    [ "core::Pair< T1, T2 >", "structcore_1_1Pair.html", null ],
    [ "core::Set< T >", "classcore_1_1Set.html", null ],
    [ "core::SharedPtr< T >", "classcore_1_1SharedPtr.html", null ],
    [ "core::SharedPtr< ast::symbolTable::Entry >", "classcore_1_1SharedPtr.html", null ],
    [ "core::SharedPtr< ast::symbolTable::Level >", "classcore_1_1SharedPtr.html", null ],
    [ "core::SharedPtr< CallableBase< R, Args... > >", "classcore_1_1SharedPtr.html", null ],
    [ "core::stackHead", "structcore_1_1stackHead.html", null ],
    [ "core::StartThreadOptions", "classcore_1_1StartThreadOptions.html", null ],
    [ "core::String", "classcore_1_1String.html", null ],
    [ "core::StringLiteral< N >", "structcore_1_1StringLiteral.html", null ],
    [ "core::StringStream", "classcore_1_1StringStream.html", null ],
    [ "ast::symbolTable::Table", "structast_1_1symbolTable_1_1Table.html", null ],
    [ "core::TlsHeader", "structcore_1_1TlsHeader.html", null ],
    [ "core::TlsInfo", "structcore_1_1TlsInfo.html", null ],
    [ "ast::tokens::Token", "structast_1_1tokens_1_1Token.html", null ],
    [ "core::UniquePtr< T >", "classcore_1_1UniquePtr.html", null ],
    [ "core::UniquePtr< ast::Argument >", "classcore_1_1UniquePtr.html", null ],
    [ "core::UniquePtr< ast::CastDeclaration >", "classcore_1_1UniquePtr.html", null ],
    [ "core::UniquePtr< ast::CompoundStmt >", "classcore_1_1UniquePtr.html", null ],
    [ "core::UniquePtr< ast::Declarator >", "classcore_1_1UniquePtr.html", null ],
    [ "core::UniquePtr< ast::Expression >", "classcore_1_1UniquePtr.html", null ],
    [ "core::UniquePtr< ast::FunctionDeclaration >", "classcore_1_1UniquePtr.html", null ],
    [ "core::UniquePtr< ast::OperationDeclaration >", "classcore_1_1UniquePtr.html", null ],
    [ "core::UniquePtr< ast::ProgramItem >", "classcore_1_1UniquePtr.html", null ],
    [ "core::UniquePtr< ast::Statement >", "classcore_1_1UniquePtr.html", null ],
    [ "core::UniquePtr< ast::SwitchItem >", "classcore_1_1UniquePtr.html", null ],
    [ "core::UniquePtr< ast::Type >", "classcore_1_1UniquePtr.html", null ],
    [ "core::UniquePtr< ast::VariableDeclaration >", "classcore_1_1UniquePtr.html", null ],
    [ "core::UniquePtr< gssa::MetaOperation >", "classcore_1_1UniquePtr.html", null ],
    [ "core::UniquePtr< gssa::Value >", "classcore_1_1UniquePtr.html", null ],
    [ "gssa::Value", "structgssa_1_1Value.html", null ],
    [ "gssa::ValueListAttribute", "structgssa_1_1ValueListAttribute.html", null ],
    [ "core::Variant< Ts >", "classcore_1_1Variant.html", null ],
    [ "core::Variant< AffecExpression, AddAffecExpression, SubAffecExpression, MulAffecExpression, ModAffecExpression, DivAffecExpression, LandAffecExpression, LorAffecExpression, LxorAffecExpression, BandAffecExpression, BorAffecExpression, BxorAffecExpression, LshiftAffecExpression, RshiftAffecExpression, LxorExpression, LorExpression, LandExpression, BorExpression, BxorExpression, BandExpression, NeqExpression, EqExpression, LtExpression, LeExpression, GtExpression, GeExpression, LshiftExpression, RshiftExpression, AddExpression, SubExpression, DivExpression, ModExpression, MulExpression, TernaryExpression, PreIncrExpression, PreDecrExpression, PostIncrExpression, PostDecrExpression, DerefExpression, AddrofExpression, BnotExpression, LnotExpression, SyscallExpression, SizeofExpression, ArrayExpression, PtrFieldExpression, FieldExpression, FunExpression, CastExpression, BitCastExpression, VarExpression, IntExpression, CharExpression, StringExpression, TrueExpression, FalseExpression, ThisExpression, OtherExpression >", "classcore_1_1Variant.html", [
      [ "ast::Expression", "structast_1_1Expression.html", null ]
    ] ],
    [ "core::Variant< FunctionAttribute, ValueListAttribute >", "classcore_1_1Variant.html", [
      [ "gssa::Attribute", "structgssa_1_1Attribute.html", null ]
    ] ],
    [ "core::Variant< FunctionDeclaration, StructDeclaration, UnionDeclaration, VariableDeclaration >", "classcore_1_1Variant.html", [
      [ "ast::ProgramItem", "structast_1_1ProgramItem.html", null ]
    ] ],
    [ "core::Variant< PtrType, ArrayType, FunType, BitType, VoidType, TypelessType, StructType, UnionType >", "classcore_1_1Variant.html", [
      [ "ast::Type", "structast_1_1Type.html", null ]
    ] ],
    [ "core::Variant< SwitchCase, SwitchDefault >", "classcore_1_1Variant.html", [
      [ "ast::SwitchItem", "structast_1_1SwitchItem.html", null ]
    ] ],
    [ "core::Variant< VariableDeclaration, CompoundStmt, WhileStmt, DoWhileStmt, ForStmt, IfStmt, SwitchStmt, ExpressionStmt, NopStmt, ContinueStmt, BreakStmt, ReturnStmt >", "classcore_1_1Variant.html", [
      [ "ast::Statement", "structast_1_1Statement.html", null ]
    ] ],
    [ "core::Vector< T >", "classcore_1_1Vector.html", null ],
    [ "core::Vector< core::SharedPtr< ast::symbolTable::Entry > >", "classcore_1_1Vector.html", null ],
    [ "core::Vector< core::UniquePtr< ast::Argument > >", "classcore_1_1Vector.html", null ],
    [ "core::Vector< core::UniquePtr< ast::CastDeclaration > >", "classcore_1_1Vector.html", null ],
    [ "core::Vector< core::UniquePtr< ast::Declarator > >", "classcore_1_1Vector.html", null ],
    [ "core::Vector< core::UniquePtr< ast::Expression > >", "classcore_1_1Vector.html", null ],
    [ "core::Vector< core::UniquePtr< ast::FunctionDeclaration > >", "classcore_1_1Vector.html", null ],
    [ "core::Vector< core::UniquePtr< ast::OperationDeclaration > >", "classcore_1_1Vector.html", null ],
    [ "core::Vector< core::UniquePtr< ast::ProgramItem > >", "classcore_1_1Vector.html", null ],
    [ "core::Vector< core::UniquePtr< ast::Statement > >", "classcore_1_1Vector.html", null ],
    [ "core::Vector< core::UniquePtr< ast::SwitchItem > >", "classcore_1_1Vector.html", null ],
    [ "core::Vector< core::UniquePtr< ast::Type > >", "classcore_1_1Vector.html", null ],
    [ "core::Vector< core::UniquePtr< ast::VariableDeclaration > >", "classcore_1_1Vector.html", null ],
    [ "core::Vector< core::UniquePtr< gssa::Value > >", "classcore_1_1Vector.html", null ],
    [ "core::Vector< gssa::Value * >", "classcore_1_1Vector.html", null ],
    [ "core::Vector< u32 >", "classcore_1_1Vector.html", null ],
    [ "core::Zipped< Iterable1, Iterable2 >", "classcore_1_1Zipped.html", null ]
];