name: Check and build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Lint, build and test
    runs-on: ubuntu-latest
    container:
      image: leothaud/cidmol-build:latest
      options: --user 1002:1002
    steps:
      - name: Get Template Code
        uses: actions/checkout@v4
      - name: clang-format
        uses: DoozyX/clang-format-lint-action@v0.20
        with:
          source: "./src"
          extensions: "cpp"
          clangFormatVersion: 20
      - name: Debug build
        run: |
          mkdir -p "$GITHUB_WORKSPACE/debug-build"
          cd "$GITHUB_WORKSPACE/debug-build"
          cmake -G Ninja .. -DCMAKE_BUILD_TYPE=Debug
          cmake --build .
      - name: Release build
        run: |
          mkdir -p "$GITHUB_WORKSPACE/release-build"
          cd "$GITHUB_WORKSPACE/release-build"
          cmake -G Ninja .. -DCMAKE_BUILD_TYPE=Release
          cmake --build .
      - name: Run tests
        run: |
          cd "$GITHUB_WORKSPACE/debug-build"
          cmake --build . --target test