name: Check and build

on: [push, pull_request]

jobs:
  lint:
    name: Check formatting
    runs-on: self-hosted
    steps:
      - name: Get Template Code
        uses: actions/checkout@v4
      - name: clang-format
        uses: DoozyX/clang-format-lint-action@v0.20
        with:
          source: "./src"
          extensions: "cpp"
          clangFormatVersion: 20

  build:
    name: Build and test
    runs-on: self-hosted
    container:
      image: leothaud/cidmol-build:latest
    # Request permissions to push to gh-pages branch.
    permissions:
      contents: write
    steps:
      - name: Get cidmol
        uses: actions/checkout@v4
        with:
          path: "cidmol"
      - name: Debug build
        run: |
          mkdir -p "$GITHUB_WORKSPACE/cidmol/debug-build"
          cd "$GITHUB_WORKSPACE/cidmol/debug-build"
          cmake -G Ninja .. -DCMAKE_BUILD_TYPE=Debug
          cmake --build .
      - name: Release build
        run: |
          mkdir -p "$GITHUB_WORKSPACE/cidmol/release-build"
          cd "$GITHUB_WORKSPACE/cidmol/release-build"
          cmake -G Ninja .. -DCMAKE_BUILD_TYPE=Release
          cmake --build .
